[build]
  command = "npm ci && node ./node_modules/astro/bin/astro.js build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.24.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
